### PR TITLE
6.0.0-beta.6 examples expressions transition

### PR DESCRIPTION
**Pull request by langsmith**
This pr bumps the maps sdk for android version to 6.0.0-beta.6 and updates many examples to use expressions.

### CODE REVIEW

**Comment by langsmith** [comment]
fyi @tobrun , besides potentially any examples in the `data driven styling section` , here are the examples that have issues/crashes:

- [ ] extrusions population density
- [ ] marathon extrusion
- [ ] indoor map
- [ ] wearable: location tracking

**Comment by tobrun** [comment]
#666 fixes a couple of dds section examples, the following are still remaining:
 - [ ] ChoroplethJsonVectorMixActivity
 - [ ] ChoroplethZoomChangeActivity

**Comment by langsmith** [comment]
Also needs fixing
- [ ] MultipleGeometriesActivity

**Comment by langsmith** [comment]
Traffic and GeoJSON plugins still crash. [I've commented out the two plugins so that they don't hold up this specific release](https://github.com/mapbox/mapbox-android-demo/pull/663/commits/c56c28ccb8101c6174c7243efcc02dca97d0adaf). Will ticket each one independently as well.

**Comment by langsmith** [comment]
Ok @tobrun , this is ready for review when you get a chance

**Pull request merged**
