### PR TITLE
Remove location examples

### PR DESCRIPTION
**Pull request by langsmith**
Addresses #410 

Because we now have the location plugin, this PR removes all of the location examples, layout files, strings, etc.

### CODE REVIEW

**Comment by langsmith** [comment]
Ok, removed those classes

**Comment by paulVulog** [comment]
Hi @langsmith, 

Starting with this pull request I am no more able to find a way to animate the user position marker.
I was able to find sample code such as PulseMarkerView but it is now removed.

No more sample in the Mapbox Demo app.
https://github.com/mapbox/mapbox-android-demo/issues/410 -> It seems to be replaced by the location layer. 

I we still able to animate the user position marker with Mapbox 5.1.3 ? 
Do you have some sample code for me ? 

Thx

**Comment by langsmith** [comment]
Hey @paulVulog ,

Thanks for reaching out. Right now, pulsating the location icon isn't really feasible with the location layer plugin.

Our runtime styling is very powerful and you could give it a shot to recreate pulsation. You could set up an object animator on a runtime styling symbol layer and rapidly change the iconSize (via PropertFactory) to create an effect which looks like a pulsing animation.

- [Demo app's SymbolLayer example](https://github.com/mapbox/mapbox-android-demo/blob/eadaf3a81c01f1390753dbe24b560f77d117ec27/MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/styles/SymbolLayerActivity.java)

- [`SymbolLayer` documentation](https://www.mapbox.com/android-docs/api/map-sdk/5.1.3/com/mapbox/mapboxsdk/style/layers/SymbolLayer.html)

- [`iconSize` documentation](https://www.mapbox.com/android-docs/api/map-sdk/5.1.3/com/mapbox/mapboxsdk/style/layers/PropertyFactory.html#iconSize-java.lang.Float-)

**Comment by paulVulog** [comment]
Thanks for your fast reply @langsmith.
In the near future, do you plan to add a "Pulse Effect" in the location layer plugin ?

**Comment by langsmith** [comment]
I'm not sure because I'm the not the main architect of that plugin here at Mapbox. I don't think it's on our immediate roadmap though. I assume you're asking because you'd like it to be part of the plugin? 😄 

Feel free to always [open a ticket in the plugins repo](https://github.com/mapbox/mapbox-plugins-android) if you'd like to report plugin issues and/or make plugin feature requests. Do also consider making a pull request if/when you try your hand at runtime styling the pulsing!

**Pull request merged**
