### PR TITLE
[NOT READY] Custom info window example

### PR DESCRIPTION
**Pull request by cammace**
Began working on custom info window example

### CODE REVIEW

**Comment by cammace** [comment]
> If you have many markers using different images, extending `Marker` and `baseMarkerOptions`, adding additional options such as the image, might be a better choice.

I am assuming this is what's going on in [this example](https://github.com/mapbox/mapbox-gl-native/blob/release-android-v4.1.0/platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/infowindow/InfoWindowAdapterActivity.java) @zugaldia? I wanted to keep this example simple so I just used a switch instead of creating my own `markerOptions`.

**Comment by cammace** [comment]
BTW this is what the example looks like:

ezgif com-video-to-gif

**Comment by zugaldia** [comment]
> If you have many markers using different images, extending Marker and baseMarkerOptions, adding additional options such as the image, might be a better choice.

Yeah, I like that approach better and it keeps consistency with the `TestApp`. It doesn't look right to have marker-specific data in the `InfoWindowAdapter` adapter itself.

**Comment by cammace** [comment]
Going ahead and merging this example into master, i'll create an additional example using a custom `markerOptions` in labs. This example is only meant to show how to create a custom info window using the adapter.

**Pull request merged**
