### PR TITLE
Maps SDK to v8.5.0 update

### PR DESCRIPTION
**Pull request by pengdev**
- [x] `v8.5.0-alpha.2`
- [x] `v8.5.0-alpha.3`
- [x] `v8.5.0-alpha.4`
- [x] `v8.5.0-beta.1`
- [x] stable `v8.5.0`

### CODE REVIEW

**Comment by pengdev** [comment]
### `v8.5.0-alpha.2` QA
* https://github.com/mapbox/mapbox-android-demo/issues/1222
* https://github.com/mapbox/mapbox-android-demo/issues/1247

**Comment by langsmith** [comment]
I've bumped this pr to `alpha.3`. Will do QA because @pengdev will be on vacation.

**Comment by langsmith** [comment]
### `v8.5.0-alpha.3` QA

No issues with Maps SDK. 

Black X icons appearing in circle cluster example  -> https://github.com/mapbox/mapbox-android-demo/issues/1255

**Comment by langsmith** [comment]
### `v8.5.0-alpha.4` QA

No new issues found.

**Comment by langsmith** [comment]
### `v8.5.0-beta.1` QA

Some visual artifacts have strange colors. In particular, look at parks and highways in the GIF below. Don't know if this is expected and/or whether there's any way to improve. 

ezgif com-resize

**Comment by langsmith** [comment]
### `v8.5.0` QA


No new issues found.

**Pull request merged**
