### PR TITLE
Space station current location labs demo

### PR DESCRIPTION
**Pull request by cammace**
Put this together using Retrofit and [Open Notify](http://open-notify.org/) (an open source api giving the current lat and lon position of ISS). Nowhere near done and code needs to be cleaned up of course.

ezgif com-video-to-gif 5

cc: @zugaldia @bleege

### CODE REVIEW

**Comment by zugaldia** [comment]
@cammace This is seriously awesome, what a fantastic idea.

My immediate suggestion is obviously to find a better suited icon, something that looks like ISS with a shadow. Maybe @samanpwbb can help pointing us on the right direction.

The other one, maybe for a second iteration, would be to add a polyline tracking the location.

**Comment by bleege** [comment]
I ❤️ this idea @cammace.  Very cool subject matter and great demo of the Mapbox Android SDK's tech stack and capabilities.  🚀 

The only suggestion I'd make is to NOT use [GSON](https://github.com/google/gson) for JSON parsing.  While it's a widely known and used library in the Android app world it's also a Google (note not Android) library and can give the _incorrect impression that Mapbox Android tech relies on Google and / or Google Play Services when the whole stack has been explicitly designed NOT to rely on either Google nor Google Play Services_.  While **Mapbox Android SDK tech does work with GSON** (as demonstrated by your initial commit), I'd recommend using [Android's built in JSON library](https://developer.android.com/reference/org/json/package-summary.html) or another non Google library like [`json-simple`](https://github.com/fangyidong/json-simple) for sake of this example.

**Comment by samanpwbb** [comment]
What's the goal of this demo? Code sample or something flashy to show off?

**Comment by samanpwbb** [comment]
noun project has a decent space station: https://gist.github.com/samanpwbb/93cc06243ca75be1d9a236ed3624ff18

Might be fun to blur it + make it semi-transparent so it looks like a shadow? 
noun_24414 2

If this is a flashier demo, it'd be super cool to do a split view with a visualization of the station rotating around it's orbit and also the close-up view:
screen shot 2016-06-30 at 11 40 48 am

**Comment by cammace** [comment]
>What's the goal of this demo? Code sample or something flashy to show off?
I'd say both, it's a good example showing how to update a marker in realtime tracking a real object. I like the idea of the shadow but it's really hard to see on the map

**Comment by cammace** [comment]
added marker rotation so it's point in the correct direction

**Comment by cammace** [comment]
Changed the icon so it shows up better:

screenshot_20160701-163914

Code is now complete and ready to merge!

**Pull request merged**
