### PR TITLE
Maps SDK v8.0.0

### PR DESCRIPTION
**Pull request by osana**
- [x] v7.5.0-alpha.2
- [x] v7.5.0-beta.1
- [x] v8.0.0

### CODE REVIEW

**Comment by osana** [comment]
### 7.5.0-beta.1 manual testing
Testing on ASUS Nexus 7 Android 6.0.1

Clear issue:
  - https://github.com/mapbox/mapbox-android-demo/issues/1071
  - https://github.com/mapbox/mapbox-android-demo/issues/1072

The following might get converted into issues:
   - Styles-> Add a WMS source  is showing only a map
  - Styles-> Transparent Render surface -> Can't play this video (works fine on Google Pixel 2, Android 8)
  - Styles -> Click to add photo - > Stops (works fine  on Google Pixel 2, Android 8)

**Comment by langsmith** [comment]
I changed the title of this pr to `8.0.0` because this release is now a semver major release.

**Comment by langsmith** [comment]
I've bumped the dependency to `8.0.0` to get things started. CI tests will 💥until `8.0.0` is out in a couple of hours.

**Comment by langsmith** [comment]
Once `8.0.0` is available, I will do QA and check the examples.

**Pull request merged**
