### PR TITLE
Land use example example

### PR DESCRIPTION
**Pull request by cammace**

### CODE REVIEW

**Comment by cammace** [comment]
Related ticket: https://github.com/mapbox/gl-internal/issues/503

**Comment by cammace** [comment]
Leaving a note here to add a toggle for:

- [ ] Commercial areas
- [ ] Airports?

**Comment by ivovandongen** [comment]
@cammace Small note: you have a naming issue with the `LandUseStyling` vs `LanduseStyling`. Please use `git config core.ignorecase false` to make sure git sees changes when you change filename casing.

**Comment by ivovandongen** [comment]
@cammace Fixed up the example a bit. All layers are showing now (zoom out for industrial). There is an issue with using the style api in the onMapReady callback when the style is not cached yet. Ticketed here: https://github.com/mapbox/mapbox-gl-native/issues/6032

**Pull request merged**
