### PR TITLE
remove login from china flavor

### PR DESCRIPTION
**Pull request by Chaoba**
Login is no need for China demo, so remove it and start MainActivity directly

### CODE REVIEW

**Comment by langsmith** [comment]
I/we need to keep investigating because logging in on the global flavor of this pr didn't work for me

**Comment by langsmith** [comment]
Hey sorry, I thought the login issue was with this pr. Turns out it was on `master`. I've addressed the login issue with https://github.com/mapbox/mapbox-android-demo/pull/912 and made you a reviewer. Let's merge that pr into `master` , re-base, and see how this pr performs.

**Comment by Chaoba** [comment]
@langsmith rebased, please try again.

**Comment by langsmith** [comment]
yep, everything's working great for each flavor on this branch 🚀 

giphy

**Pull request merged**
