### PR TITLE
Location picker example

### PR DESCRIPTION
**Pull request by cammace**
location_picker

Similar to @bleege's example except I'm using view annotation marker and positioning the initial camera position is done differently. 

Things that still need to be finished:
- [x] Geocoder added
- [x] Change marker to use same icon as imageview

cc: @zugaldia @tobrun @ivovandongen

### CODE REVIEW

**Comment by cammace** [comment]
Added description for the labs category: 

screenshot_20160616-155052

**Comment by cammace** [comment]
Location picker is now finished example with a bunch of commenting throughout.

**Comment by zugaldia** [comment]
@cammace Could you post an updated GIF, or is https://github.com/mapbox/mapbox-android-demo/pull/84#issue-160568394 still accurate?

**Comment by cammace** [comment]
Updated GIF @zugaldia :
ezgif com-video-to-gif

Opened an issue for the info window bug you see in the gif: https://github.com/mapbox/mapbox-gl-native/issues/5384

**Comment by chasten** [comment]
How should I know a map finish move and I only find onMapChanged(int change) method

**Comment by tobrun** [comment]
@chasten you should be able to determine if move have finished with `onMapChanged`, the int change resembles the state of the Map. You can find the definition of those states in `MapView`. Note that we support some facility methods on the camera methods that allow you to define a callback when an animation is canceled or finished.

**Pull request merged**
