### PR TITLE
Bumped demo and wearable demo up to beta.2

### PR DESCRIPTION
**Pull request by langsmith**
Updated gradle dependency lines

### CODE REVIEW

**Comment by langsmith** [comment]
**Note:** Don't merge until beta.2 is actually available for download, Maven, etc.

**Comment by langsmith** [comment]
Tests are failing because of LOSTin the Android _Wearable_ app 
screen shot 2017-05-12 at 4 56 46 pm

Related to https://github.com/mapbox/mapbox-java/issues/401?
Related to https://github.com/mapbox/mapbox-gl-native/pull/8872?

I'm not sure what to manipulate. Little guidance @tobrun or @zugaldia ?

**Comment by cammace** [comment]
This should do the job:
```java
// Mapbox Maps SDK
    compile ('com.mapbox.mapboxsdk:mapbox-android-sdk:5.1.0-beta.2@aar') {
        transitive = true
        exclude module: 'lost'
        exclude module: 'mapbox-java-geojson'
        exclude module: 'mapbox-android-telemetry'
    }
```

**Comment by zugaldia** [comment]
Why are those exclusions needed on the wearable module, but not in the mobile app?

**Comment by langsmith** [comment]
More LOST issues preventing the test build from passing. Thoughts? Remedies?

screen shot 2017-05-15 at 10 29 28 am

**Comment by zugaldia** [comment]
@langsmith Looks like you're hitting https://github.com/mapbox/mapbox-gl-native/issues/8999.

**Comment by langsmith** [comment]
Thanks @zugaldia

**Comment by langsmith** [comment]
@zugaldia , with the LOST fix, this PR's tests now pass. Approve so that I can merge?

**Pull request merged**
