### PR TITLE
Adding ignore sign in button

### LINKED ISSUE #494: Add exponential backoff
When the app is started up, the user is triggered to create or sign into their mapbox account. While it's a great feature to attract new mapbox users. It's also annoying when you don't want to use this. The dialog is shown for every app launch. To improve UX arround this, I'm suggesting adding exponential backoff to this flow so that I'm not triggered constantly (but only once in a while).

cc @zugaldia

### PR DESCRIPTION
**Pull request by langsmith**
Because the pitchforks are being sharpened over the `LandingActivity` account login/creation page (😉), this pr adds a `Don't ask again` button. This saves a boolean into SharedPreferences, which helps control whether `LandingActivity` is shown upon app launch. This pr also adds an account login/creation button to the app's settings dialog. Clicking the button brings the user to the `LandingActivity`. 

Resolves #494 

ezgif com-resize (2)

ezgif com-resize (3)

### CODE REVIEW

**Comment by osana** [comment]
@langsmith This is nitpicking a bit.
Here is the Action flow: 
  Start app-> Login shown ->  Do not ask again pressed ->  Examples shown -> Exit
  Start app -> Examples shown -> Exit
  Start app -> Examples shown -> Side drawer -> Settings -> Login Screen
  Start app-> Login shown  

I think what confused me was having a button in a Settings screen.
Settings Screen is usually a bunch of  Settings that are turned off/on/initialized
Showing a Login screen seems more of an Action and I would expect it to be above the Settings Menu Item (that would be there only if you are not Logged In). And Setting screen would have a toggle next to some version of :  `Always Show Landing Screen`

**Comment by langsmith** [comment]
>Showing a Login screen seems more of an Action and I would expect it to be above the Settings Menu Item (that would be there only if you are not Logged In). And Setting screen would have a toggle next to some version of : Always Show Landing Screen

@osana , thanks for the feedback. Just pushed a commit that adds your suggestions.

**Comment by osana** [comment]
@langsmith Looks very good.
One more request - could we have a checkbox next to (as @zugaldia  initially suggested) 
We all know that those labels are clickable but that is not obvious for newcomers

**Comment by zugaldia** [comment]
@langsmith could you post a still screenshot of the proposed landing page?

**Comment by langsmith** [comment]
> proposed landing page

@zugaldia , I'm unclear on what you mean.

#### Here are visuals of what this pr adds as of now:

New `go to login screen` nav drawer menu item. This is only shown if the user isn't logged into a mapbox account:
Screen Shot 2019-04-18 at 7 27 20 AM

New switch option in settings dialog:
Screen Shot 2019-04-18 at 7 27 06 AM

New `don't ask again` button on `LandingActivity`. This is what @osana 's requested be a checkbox, rather than a button:
Screen Shot 2019-04-18 at 7 29 19 AM

**Comment by osana** [comment]
@langsmith I meant having a checkbox next to `Don't ask again` ( I believe @zugaldia  mentioned that on slack - if I am not mistaken)
Settings pop-up -  🥗 
Navigation Drawer - 🥗

**Comment by zugaldia** [comment]
>  I'm unclear on what you mean.

Sorry - I meant a screenshot of the first screen users would see on a fresh install (the one with the astronaut and the sign-in buttons). You show it on your video, but it goes too fast to look into it in detail.

**Comment by langsmith** [comment]
device-2019-04-19-101739 copy

**Comment by osana** [comment]
@langsmith For some reason, I could not switch to the branch to run it again. 
The screenshot is exactly what I meant.

Once case to check is the following:
1) First Launch-> Login -> check be the box to ignore login-> List is displayed
Nav Drawer -> Login  -> The Login screen should appear with the checkox checked 
Quit the app

Restart should NOT show the Login ( in settings it the  value is set to NOT show the login)

2) First Launch-> Login -> check be the box to ignore login-> List is displayed
Nav Drawer -> Login  -> The Login screen should appear with the checkox checked 
Uncheck the checkbox
Quit the app

Restart should SHOW the Login  ( in settings  the  value is set to SHOW the login)

**Comment by langsmith** [comment]
Ok @osana . My latest commit and rebase have addressed the two scenarios that you described above.

**Pull request merged**
