### PR TITLE
getStyle() should not be called without a listener

### LINKED ISSUE #1068: SimplifyPolylineActivity : java.lang.IllegalStateException: Style hasn't been fully initialised
From Firebase: 
```
java.lang.IllegalStateException: Style hasn't been fully initialised
FATAL EXCEPTION: main
Process: com.mapbox.mapboxandroiddemo.debug, PID: 11283
java.lang.IllegalStateException: Style hasn't been fully initialised
	at com.mapbox.mapboxandroiddemo.examples.javaservices.SimplifyPolylineActivity.addLine(SimplifyPolylineActivity.java:181)
	at com.mapbox.mapboxandroiddemo.examples.javaservices.SimplifyPolylineActivity.drawBeforeSimplify(SimplifyPolylineActivity.java:163)
	at com.mapbox.mapboxandroiddemo.examples.javaservices.SimplifyPolylineActivity.drawLines(SimplifyPolylineActivity.java:157)
	at com.mapbox.mapboxandroiddemo.examples.javaservices.SimplifyPolylineActivity.access$100(SimplifyPolylineActivity.java:40)
	at com.mapbox.mapboxandroiddemo.examples.javaservices.SimplifyPolylineActivity$DrawGeoJson.onPostExecute(SimplifyPolylineActivity.java:148)
	at com.mapbox.mapboxandroiddemo.examples.javaservices.SimplifyPolylineActivity$DrawGeoJson.onPostExecute(SimplifyPolylineActivity.java:116)
	at android.os.AsyncTask.finish(AsyncTask.java:695)
	at android.os.AsyncTask.-wrap1(Unknown Source:0)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:712)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6541)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
```

There needs to be a check for `style != null`  when FeatureCollection is set

### PR DESCRIPTION
**Pull request by osana**
Closes #1068

### CODE REVIEW

**Comment by osana** [comment]
@tobrun @LukasPaczos could you 👀 on this. I want to make sure we are not covering a bug in `android maps` by applying this fix. 

We are starting FeatureCollection loading form `onStyleLoaded` when style was already loaded. I would think that once style was loaded map.getStyle() should reliably return the loaded style. Is that correct?

**Comment by LukasPaczos** [comment]
This looks like a red herring. Are you able to reproduce test failures locally? If so, could you debug the route from `MapboxMap#notifyStyleLoaded` to the point of crash? Is the `Style` object correctly marked as fully loaded so that it can be returned in the `MapboxMap#getStyle`?

**Comment by osana** [comment]
I could never reproduce it locally but tests are failing. 
It did not make sense to me at all.
@langsmith also suggested that the way we run tests could the culprit.

**Comment by LukasPaczos** [comment]
Closing in favor of https://github.com/mapbox/mapbox-android-demo/pull/1076.

**Pull request closed without merging**
