### PR TITLE
Adds wear module

### PR DESCRIPTION
**Pull request by zugaldia**
This PR adds a wear module and brings the equivalent of `SimpleMapViewActivity` to watches.

Work in progress.

/cc: @cammace

### CODE REVIEW

**Comment by cammace** [comment]
Any reason for not extending `WearableActivity` @zugaldia?

**Comment by cammace** [comment]
CI keeps failing with this exception:

```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':MapboxAndroidWearDemo'.
> You have not accepted the license agreements of the following SDK components:
  [Google Repository].
  Before building your project, you need to accept the license agreements and complete the installation of the missing components using the Android Studio SDK Manager.
  Alternatively, to learn how to transfer the license agreements from one workstation to another, go to http://d.android.com/r/studio-ui/export-licenses.html
```

I can transfer the license in my android folder to Bitrise but i'm not sure where the place them.

**Comment by zugaldia** [comment]
> Any reason for not extending WearableActivity @zugaldia?

None, and good catch. The code in the original PR is the boilerplate code that AS gave me when I created a blank Wear activity. 

> I can transfer the license in my android folder to Bitrise but i'm not sure where the place them.

The licenses are in `<android sdk home path>/licenses`. Reading on [Bitrise's Android Docker environment](http://devcenter.bitrise.io/docs/android-environment-whats-pre-installed) looks like we should try `$ANDROID_HOME/licenses`.

**Comment by cammace** [comment]
Here's what the map looks like on the Huawei watch running Android Wear 2.0. You'll notice that all the map widgets are cut off (including compass) and the attribution buttons missing (even when enabling in XML). I also hide the zoom buttons in XML. 

screen

Next steps will be to introduce the [`WearableRecyclerView`](https://developer.android.com/wear/preview/features/wearable-recycler-view.html?utm_campaign=android_discussion_wearpreview_092916&utm_source=anddev&utm_medium=blog) introduced in Android wear 2.0 beta 3 into the MainActivity instead of the map. This will give us room to add additional examples to the app. When ready, we can also publish the app separately to the wear PlayStore.

**Comment by cammace** [comment]
I've created the `WearableRecyclerView`:

screen 1

adding examples to this app's now almost identical to how you'd add them in the Android module. Once CI Approves, i'll merge!

**Pull request merged**
