### PR TITLE
Examples added within app

### PR DESCRIPTION
**Pull request by cammace**
I've stripped the app down and added all the examples as discussed in mapbox/android-sdk#129. Versioning for this app appears to be in sync with the mapbox android SDK. Bumped it to `4.1.0` for anticipation of next release. Besides that, bugs still need to be squashed, code cleanup, and testing on different devices. 

cc: @tobrun @bleege

### CODE REVIEW

**Comment by bleege** [comment]
@cammace Awesome.  Are you holding this until `4.1.0` drops and then we'll merge?

**Comment by cammace** [comment]
@bleege I've implemented things such as `MapboxAccountManager` which is only available on 4.1.0. It also gives time to polish the app and add additional examples if we wait.

**Comment by bleege** [comment]
@cammace Cool.  Feel free to merge this in when you're feeling good about the basic setup / stability.  We can leave it pointed at `4.1.0-SNAPSHOT` for now so that we have time to let the dust settle.  We can then update to `4.1.0` when it drops and push there.

BTW, can you also create a new issue in this repo that describes what this refactor is all about?  The original comment links to internal content and it'd be helpful for everyone to understand what and why we're working on this.

**Comment by cammace** [comment]
As discussed, App is stable and ready to be merged.

**Pull request merged**
