### PR TITLE
Bumped navigation dependency line to 0.4.0

### PR DESCRIPTION
**Pull request by langsmith**
Part of [the Nav SDK 0.4.0 release](https://github.com/mapbox/mapbox-navigation-android/issues/152)

### CODE REVIEW

**Comment by cammace** [comment]
RouteUtils doesn't exist anymore in the navigation SDK, we should remove the offroute example and remove this dependency if it's not being used anymore in the demo app.

**Comment by langsmith** [comment]
Example, strings, manifest line, red car .png, etc.  are all now removed

Nav sdk dependency line is also removed

**Comment by elmustaphah** [comment]
Why has the class RouteUtils been removed?

**Comment by cammace** [comment]
RouteUtils was an initial prototype of our navigation SDK and since it's creation, logic for navigation has been becoming increasingly more complex, smarter, and more efficient. Now that the Navigation SDKs available in beta, we determined that the RouteUtils methods were no longer up to the quality one should expect inside their navigation app. Feel free to reach out through our contact page if you have any additional questions/feedback.

**Pull request merged**
