### PR TITLE
Maps SDK v7.4.0

### PR DESCRIPTION
**Pull request by LukasPaczos**
- [x] v7.4.0-alpha.1
- [x] v7.4.0-alpha.2
- [x] v7.4.0-beta.1
- [x] v7.4.0

### CODE REVIEW

**Comment by LukasPaczos** [comment]
`v7.4.0-alpha.1` QA results:
- clearer stack trace for https://github.com/mapbox/mapbox-android-demo/issues/828
- duplicate activity https://github.com/mapbox/mapbox-android-demo/issues/1021
- `AddWmsSourceActivity` fails to load tiles https://github.com/mapbox/mapbox-android-demo/issues/1020

Improvement ideas:
- use cache pre-warm API https://github.com/mapbox/mapbox-android-demo/issues/1022

**Comment by langsmith** [comment]
#1021 being resolved by https://github.com/mapbox/mapbox-android-demo/pull/1024

**Comment by LukasPaczos** [comment]
`v7.4.0-alpha.2` QA results:
- incorrect layer ordering (reproducible with the highlighted line example), fixed by https://github.com/mapbox/mapbox-gl-native/pull/14408

**Comment by langsmith** [comment]
No issues with `v7.4.0-beta.1`

**Comment by langsmith** [comment]
No issues with stable `7.4.0`. Good to go @osana

**Comment by LukasPaczos** [comment]
This needs to be rebased on top of https://github.com/mapbox/mapbox-android-demo/pull/1076 when merged.

**Pull request merged**
