### PR TITLE
update Android Maps SDK to 8.2.0

### PR DESCRIPTION
**Pull request by tobrun**
This PR updates the Mapbox Maps SDK dependency to 8.2.0

### CODE REVIEW

**Comment by langsmith** [comment]
alpha.3 QA didn't happen. I bumped to `beta.1` and here's what I found that's worth mentioning:

Weird `SymbolLayer` flashing in `MissingIconActivity`:

ezgif com-resize (1)

Here's how the `SymbolLayer` in that activity is styled with DDS:

```java
style.addLayer(new SymbolLayer(ICON_LAYER_ID, ICON_SOURCE_ID).withProperties(
                iconImage(get(PROFILE_NAME)),
                iconIgnorePlacement(true),
                iconAllowOverlap(true),
                textField(get(PROFILE_NAME)),
                textIgnorePlacement(true),
                textAllowOverlap(true),
                textOffset(new Float[] {0f, 2f})
              ));
```


Weird `CircleLayer` flashing in `StyleCirclesCategoricallyActivity`:

ezgif com-resize (2)

**Comment by LukasPaczos** [comment]
> Weird SymbolLayer flashing in MissingIconActivity:

I wasn't able to reproduce, does it happen on earlier pre-releases? Could you replicate in gl-native?

> Weird CircleLayer flashing in StyleCirclesCategoricallyActivity

Looks like a geometry simplification, @tmpsantos is this expected for mbtiles? Here's the [tileset](http://api.mapbox.com/v4/examples.8fgz4egr.json).

**Comment by tmpsantos** [comment]
> Looks like a geometry simplification

Looks a bit like what we tried to fix with https://github.com/mapbox/mapbox-gl-native/pull/13963 but it did not work. The proper fix would have a considerable perf impact and we decided not to do it for now.

**Comment by langsmith** [comment]
>I wasn't able to reproduce, does it happen on earlier pre-releases? Could you replicate in gl-native?

Branched off of `release-pickle-juice` and tried to reproduce in the Maps SDK test app https://github.com/mapbox/mapbox-gl-native/compare/release-picklejuice...ls-missing-icon-flicker-test?expand=1 . Couldn't reproduce it. 

ezgif com-resize (7)


👇 Demo app with `alpha.3`

ezgif com-resize (8)

Couldn't even reproduce when I did a clean install of the demo app on `8.2.0-beta.1`.

**Pull request merged**
