### PR TITLE
Show selected marker using layer

### PR DESCRIPTION
**Pull request by snijsure**
Show a selected marker using layer

selected

### CODE REVIEW

**Comment by snijsure** [comment]
@langsmith @tobrun  Here is the pull request that adds concept of selected marker. You can merge if you wish to.

**Comment by langsmith** [comment]
Thank you, thank you @snijsure . I will make the needed adjustments to other parts of the app so that this example is included

**Comment by langsmith** [comment]
For some reason, I'm not able to hop on this branch/pr to add more edits. Closing this and moving the changes over to #498

**Comment by snijsure** [comment]
👍 thanks for taking care of this @langsmith

**Pull request closed without merging**
